### Create User
POST http://localhost:8080/api/users
Content-Type: application/json

{
    "username": "John Doe",
    "email": "johndoe@example.com"
}


### Get User by ID
GET http://localhost:8080/api/users/1


### Update User
PUT http://localhost:8080/api/users/1
Content-Type: application/json

{
    "username": "Updated Name",
    "email": "updated@example.com"
}


### Delete User
DELETE http://localhost:8080/api/users/1


### Create Transaction
POST http://localhost:8080/api/transactions
Content-Type: application/json

{
    "type": "Payment",
    "amount": 100.00,
    "description": "Payment",
    "user": {
        "id": 1
    }
}


### Get Transaction by ID
GET http://localhost:8080/api/transactions/1


### Get Transactions by User ID
GET http://localhost:8080/api/transactions/user/1


### Update Transaction
PUT http://localhost:8080/api/transactions/1
Content-Type: application/json

{
    "type": "Updated Payment",
    "amount": 200.00,
    "description": "Payment is Updated",
    "user": {
        "id": 1
    }
}


### Delete Transaction
DELETE http://localhost:8080/api/transactions/1
